# Generated by Django 4.2.5 on 2023-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('prodCode', models.CharField(help_text='Enter the product code.', max_length=40, primary_key=True, serialize=False, verbose_name='Product Code')),
                ('prodDesc', models.TextField(blank=True, null=True)),
                ('prodPrice', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
