# Generated by Django 4.2.5 on 2023-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='prodCurrency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='prodSupplier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
