# Generated by Django 4.2.5 on 2023-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0002_pricelist_prodcurrency_pricelist_prodsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateDate', models.DateField()),
                ('rateBaseCurrency', models.CharField(max_length=3)),
                ('rateTargetCurrency', models.CharField(max_length=3)),
                ('rateValue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rateUpdatedBy', models.CharField(max_length=100)),
                ('rateUpdatedOn', models.DateField()),
            ],
        ),
    ]
