# Generated by Django 4.2.5 on 2023-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0003_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('prodCode', models.CharField(help_text='Enter the product code.', max_length=40, primary_key=True, serialize=False, verbose_name='Product Code')),
                ('prodDesc', models.TextField(blank=True, null=True)),
                ('prodCategory', models.CharField(max_length=255, verbose_name='Product Category')),
                ('prodDOC', models.DateTimeField(verbose_name='Date of Creation')),
            ],
        ),
    ]
