# Generated by Django 4.2.5 on 2023-10-09 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0005_alter_masterinventory_proddoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostMapping',
            fields=[
                ('prodSupplierCode', models.CharField(help_text='Enter the product supplier code.', max_length=40, primary_key=True, serialize=False, verbose_name='Product Supplier Code')),
                ('prodNashuaCode', models.CharField(blank=True, help_text='Enter the product nashua code.', max_length=40, null=True, verbose_name='Product Nashua Code')),
                ('prodDesc', models.TextField(blank=True, null=True)),
                ('prodCategory', models.CharField(max_length=255, verbose_name='Product Category')),
                ('prodSupplierName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('prodSupplierCurrency', models.CharField(blank=True, max_length=3, null=True)),
                ('prodSupplierCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('prodSupplierLandedCost_USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('prodNashuaSellingPrice_USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('prodCalculatedPriceDate', models.DateField(default=datetime.date.today, verbose_name='Calculated On')),
            ],
        ),
    ]
