# Generated by Django 4.2.5 on 2023-10-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0006_productcostmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcostmapping',
            name='prodExempt',
            field=models.CharField(default='Null', max_length=50, verbose_name='Exempt on Calculation'),
        ),
    ]
