# Generated by Django 4.2.5 on 2023-10-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0007_productcostmapping_prodexempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostingFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockCategory', models.CharField(max_length=255, verbose_name='Product Category')),
                ('SupplierName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('ExchangeRateFactor', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('DutyFactor', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('FreightChargesFactor', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('MarkupFactor', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
        ),
    ]
