# Generated by Django 4.2.5 on 2023-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0008_productcostingfactors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcostingfactors',
            name='UpdatedBy',
            field=models.CharField(default='Nill', max_length=100),
        ),
        migrations.AddField(
            model_name='productcostingfactors',
            name='UpdatedOn',
            field=models.DateField(auto_now=True),
        ),
    ]
