# Generated by Django 4.2.5 on 2023-10-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0009_productcostingfactors_updatedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcostingfactors',
            name='UpdatedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcostingfactors',
            name='UpdatedOn',
            field=models.DateField(),
        ),
    ]
