# Generated by Django 4.2.5 on 2023-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0010_alter_productcostingfactors_updatedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcostmapping',
            name='prodExempt',
        ),
        migrations.AddField(
            model_name='productcostmapping',
            name='prodCalculationModifier',
            field=models.CharField(default='Null', max_length=50, verbose_name='Modify on Calculation'),
        ),
    ]
