# Generated by Django 4.2.5 on 2023-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0011_remove_productcostmapping_prodexempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcostmapping',
            name='prodCalculationModifier',
            field=models.CharField(default='Null', max_length=50, verbose_name='Modify Method on Calculation'),
        ),
    ]
