# Generated by Django 4.2.5 on 2023-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0012_alter_productcostmapping_prodcalculationmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcostmapping',
            name='prodSupplierCostUSD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
