# Generated by Django 4.2.5 on 2023-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0013_productcostmapping_prodsuppliercostusd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
                ('Contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedBy', models.CharField(max_length=100)),
                ('CreatedOn', models.DateField()),
            ],
        ),
    ]
