# Generated by Django 4.2.5 on 2023-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0015_userdepartment_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinventory',
            name='prodID',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='productcostmapping',
            name='prodID',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
