# Generated by Django 4.2.5 on 2023-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceSync', '0017_alter_masterinventory_prodcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcostingfactors',
            name='ExchangeRateFactor',
        ),
        migrations.AddField(
            model_name='productcostingfactors',
            name='CalculationModifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
